### ISSUE TITLE
More fluid nano

### ISSUE THREAD

**Issue by Joohansson** [bra1n/cryptolights#3]
The nano tx comes in batches every 5-10 sec. The other coins are more fluid. Maybe the nanode api don't allow tighter updates but perhaps build a module to allow it to work with local RPC calls if you run your own node?

**Comment by bra1n** [comment]
At the moment, there don't seem to be almost no transactions at all, so the issue currently seems moot. However, when / if it arises again, I'd suggest simply putting artificial delays between the batches of transactions. So that there always is a (short) delay between each individual block rather than a big delay between a bunch of simultaneous blocks. I'll look into it when Nano transactions pick up again. ;)
